version: "3.8"

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: mikkaiser/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: mikkaiser/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - 8080:80

networks:
  laranet:
    driver: bridge
